// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: mq_msg.proto
// Protobuf C++ Version: 5.29.3

#include "mq_msg.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace bitmq {

inline constexpr BasicProperties::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : id_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        routing_key_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        delivery_mode_{static_cast< ::bitmq::DeliveryMode >(0)},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR BasicProperties::BasicProperties(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct BasicPropertiesDefaultTypeInternal {
  PROTOBUF_CONSTEXPR BasicPropertiesDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~BasicPropertiesDefaultTypeInternal() {}
  union {
    BasicProperties _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 BasicPropertiesDefaultTypeInternal _BasicProperties_default_instance_;

inline constexpr Message_Payload::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        body_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        valid_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        properties_{nullptr} {}

template <typename>
PROTOBUF_CONSTEXPR Message_Payload::Message_Payload(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct Message_PayloadDefaultTypeInternal {
  PROTOBUF_CONSTEXPR Message_PayloadDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~Message_PayloadDefaultTypeInternal() {}
  union {
    Message_Payload _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 Message_PayloadDefaultTypeInternal _Message_Payload_default_instance_;

inline constexpr Message::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        payload_{nullptr},
        offset_{0u},
        length_{0u} {}

template <typename>
PROTOBUF_CONSTEXPR Message::Message(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct MessageDefaultTypeInternal {
  PROTOBUF_CONSTEXPR MessageDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~MessageDefaultTypeInternal() {}
  union {
    Message _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 MessageDefaultTypeInternal _Message_default_instance_;
}  // namespace bitmq
static const ::_pb::EnumDescriptor* file_level_enum_descriptors_mq_5fmsg_2eproto[2];
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_mq_5fmsg_2eproto = nullptr;
const ::uint32_t
    TableStruct_mq_5fmsg_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::bitmq::BasicProperties, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::bitmq::BasicProperties, _impl_.id_),
        PROTOBUF_FIELD_OFFSET(::bitmq::BasicProperties, _impl_.delivery_mode_),
        PROTOBUF_FIELD_OFFSET(::bitmq::BasicProperties, _impl_.routing_key_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message_Payload, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message_Payload, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::bitmq::Message_Payload, _impl_.properties_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message_Payload, _impl_.body_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message_Payload, _impl_.valid_),
        0,
        ~0u,
        ~0u,
        PROTOBUF_FIELD_OFFSET(::bitmq::Message, _impl_._has_bits_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::bitmq::Message, _impl_.payload_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message, _impl_.offset_),
        PROTOBUF_FIELD_OFFSET(::bitmq::Message, _impl_.length_),
        0,
        ~0u,
        ~0u,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::bitmq::BasicProperties)},
        {11, 22, -1, sizeof(::bitmq::Message_Payload)},
        {25, 36, -1, sizeof(::bitmq::Message)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::bitmq::_BasicProperties_default_instance_._instance,
    &::bitmq::_Message_Payload_default_instance_._instance,
    &::bitmq::_Message_default_instance_._instance,
};
const char descriptor_table_protodef_mq_5fmsg_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\014mq_msg.proto\022\005bitmq\"^\n\017BasicProperties"
    "\022\n\n\002id\030\001 \001(\t\022*\n\rdelivery_mode\030\002 \001(\0162\023.bi"
    "tmq.DeliveryMode\022\023\n\013routing_key\030\003 \001(\t\"\246\001"
    "\n\007Message\022\'\n\007payload\030\001 \001(\0132\026.bitmq.Messa"
    "ge.Payload\022\016\n\006offset\030\002 \001(\r\022\016\n\006length\030\003 \001"
    "(\r\032R\n\007Payload\022*\n\nproperties\030\001 \001(\0132\026.bitm"
    "q.BasicProperties\022\014\n\004body\030\002 \001(\t\022\r\n\005valid"
    "\030\003 \001(\t*A\n\014ExchangeType\022\016\n\nUNKNOWTYPE\020\000\022\n"
    "\n\006DIRECT\020\001\022\n\n\006FANOUT\020\002\022\t\n\005TOPIC\020\003*:\n\014Del"
    "iveryMode\022\016\n\nUNKNOWMODE\020\000\022\r\n\tUNDURABLE\020\001"
    "\022\013\n\007DURABLE\020\002b\006proto3"
};
static ::absl::once_flag descriptor_table_mq_5fmsg_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_mq_5fmsg_2eproto = {
    false,
    false,
    421,
    descriptor_table_protodef_mq_5fmsg_2eproto,
    "mq_msg.proto",
    &descriptor_table_mq_5fmsg_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_mq_5fmsg_2eproto::offsets,
    file_level_enum_descriptors_mq_5fmsg_2eproto,
    file_level_service_descriptors_mq_5fmsg_2eproto,
};
namespace bitmq {
const ::google::protobuf::EnumDescriptor* ExchangeType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_mq_5fmsg_2eproto);
  return file_level_enum_descriptors_mq_5fmsg_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t ExchangeType_internal_data_[] = {
    262144u, 0u, };
bool ExchangeType_IsValid(int value) {
  return 0 <= value && value <= 3;
}
const ::google::protobuf::EnumDescriptor* DeliveryMode_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_mq_5fmsg_2eproto);
  return file_level_enum_descriptors_mq_5fmsg_2eproto[1];
}
PROTOBUF_CONSTINIT const uint32_t DeliveryMode_internal_data_[] = {
    196608u, 0u, };
bool DeliveryMode_IsValid(int value) {
  return 0 <= value && value <= 2;
}
// ===================================================================

class BasicProperties::_Internal {
 public:
};

BasicProperties::BasicProperties(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bitmq.BasicProperties)
}
inline PROTOBUF_NDEBUG_INLINE BasicProperties::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::bitmq::BasicProperties& from_msg)
      : id_(arena, from.id_),
        routing_key_(arena, from.routing_key_),
        _cached_size_{0} {}

BasicProperties::BasicProperties(
    ::google::protobuf::Arena* arena,
    const BasicProperties& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  BasicProperties* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.delivery_mode_ = from._impl_.delivery_mode_;

  // @@protoc_insertion_point(copy_constructor:bitmq.BasicProperties)
}
inline PROTOBUF_NDEBUG_INLINE BasicProperties::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : id_(arena),
        routing_key_(arena),
        _cached_size_{0} {}

inline void BasicProperties::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.delivery_mode_ = {};
}
BasicProperties::~BasicProperties() {
  // @@protoc_insertion_point(destructor:bitmq.BasicProperties)
  SharedDtor(*this);
}
inline void BasicProperties::SharedDtor(MessageLite& self) {
  BasicProperties& this_ = static_cast<BasicProperties&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.id_.Destroy();
  this_._impl_.routing_key_.Destroy();
  this_._impl_.~Impl_();
}

inline void* BasicProperties::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) BasicProperties(arena);
}
constexpr auto BasicProperties::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(BasicProperties),
                                            alignof(BasicProperties));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull BasicProperties::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_BasicProperties_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &BasicProperties::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<BasicProperties>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &BasicProperties::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<BasicProperties>(), &BasicProperties::ByteSizeLong,
            &BasicProperties::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_._cached_size_),
        false,
    },
    &BasicProperties::kDescriptorMethods,
    &descriptor_table_mq_5fmsg_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* BasicProperties::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 43, 2> BasicProperties::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bitmq::BasicProperties>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string id = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_.id_)}},
    // .bitmq.DeliveryMode delivery_mode = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(BasicProperties, _impl_.delivery_mode_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_.delivery_mode_)}},
    // string routing_key = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_.routing_key_)}},
  }}, {{
    65535, 65535
  }}, {{
    // string id = 1;
    {PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_.id_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // .bitmq.DeliveryMode delivery_mode = 2;
    {PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_.delivery_mode_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kOpenEnum)},
    // string routing_key = 3;
    {PROTOBUF_FIELD_OFFSET(BasicProperties, _impl_.routing_key_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }},
  // no aux_entries
  {{
    "\25\2\0\13\0\0\0\0"
    "bitmq.BasicProperties"
    "id"
    "routing_key"
  }},
};

PROTOBUF_NOINLINE void BasicProperties::Clear() {
// @@protoc_insertion_point(message_clear_start:bitmq.BasicProperties)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.id_.ClearToEmpty();
  _impl_.routing_key_.ClearToEmpty();
  _impl_.delivery_mode_ = 0;
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* BasicProperties::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const BasicProperties& this_ = static_cast<const BasicProperties&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* BasicProperties::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const BasicProperties& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:bitmq.BasicProperties)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // string id = 1;
          if (!this_._internal_id().empty()) {
            const std::string& _s = this_._internal_id();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bitmq.BasicProperties.id");
            target = stream->WriteStringMaybeAliased(1, _s, target);
          }

          // .bitmq.DeliveryMode delivery_mode = 2;
          if (this_._internal_delivery_mode() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteEnumToArray(
                2, this_._internal_delivery_mode(), target);
          }

          // string routing_key = 3;
          if (!this_._internal_routing_key().empty()) {
            const std::string& _s = this_._internal_routing_key();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bitmq.BasicProperties.routing_key");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:bitmq.BasicProperties)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t BasicProperties::ByteSizeLong(const MessageLite& base) {
          const BasicProperties& this_ = static_cast<const BasicProperties&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t BasicProperties::ByteSizeLong() const {
          const BasicProperties& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:bitmq.BasicProperties)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string id = 1;
            if (!this_._internal_id().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_id());
            }
            // string routing_key = 3;
            if (!this_._internal_routing_key().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_routing_key());
            }
            // .bitmq.DeliveryMode delivery_mode = 2;
            if (this_._internal_delivery_mode() != 0) {
              total_size += 1 +
                            ::_pbi::WireFormatLite::EnumSize(this_._internal_delivery_mode());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void BasicProperties::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<BasicProperties*>(&to_msg);
  auto& from = static_cast<const BasicProperties&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:bitmq.BasicProperties)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_id().empty()) {
    _this->_internal_set_id(from._internal_id());
  }
  if (!from._internal_routing_key().empty()) {
    _this->_internal_set_routing_key(from._internal_routing_key());
  }
  if (from._internal_delivery_mode() != 0) {
    _this->_impl_.delivery_mode_ = from._impl_.delivery_mode_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void BasicProperties::CopyFrom(const BasicProperties& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitmq.BasicProperties)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void BasicProperties::InternalSwap(BasicProperties* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.id_, &other->_impl_.id_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.routing_key_, &other->_impl_.routing_key_, arena);
  swap(_impl_.delivery_mode_, other->_impl_.delivery_mode_);
}

::google::protobuf::Metadata BasicProperties::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Message_Payload::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Message_Payload>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_._has_bits_);
};

Message_Payload::Message_Payload(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bitmq.Message.Payload)
}
inline PROTOBUF_NDEBUG_INLINE Message_Payload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::bitmq::Message_Payload& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        body_(arena, from.body_),
        valid_(arena, from.valid_) {}

Message_Payload::Message_Payload(
    ::google::protobuf::Arena* arena,
    const Message_Payload& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Message_Payload* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.properties_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::bitmq::BasicProperties>(
                              arena, *from._impl_.properties_)
                        : nullptr;

  // @@protoc_insertion_point(copy_constructor:bitmq.Message.Payload)
}
inline PROTOBUF_NDEBUG_INLINE Message_Payload::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0},
        body_(arena),
        valid_(arena) {}

inline void Message_Payload::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.properties_ = {};
}
Message_Payload::~Message_Payload() {
  // @@protoc_insertion_point(destructor:bitmq.Message.Payload)
  SharedDtor(*this);
}
inline void Message_Payload::SharedDtor(MessageLite& self) {
  Message_Payload& this_ = static_cast<Message_Payload&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.body_.Destroy();
  this_._impl_.valid_.Destroy();
  delete this_._impl_.properties_;
  this_._impl_.~Impl_();
}

inline void* Message_Payload::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Message_Payload(arena);
}
constexpr auto Message_Payload::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Message_Payload),
                                            alignof(Message_Payload));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Message_Payload::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Message_Payload_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Message_Payload::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Message_Payload>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Message_Payload::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Message_Payload>(), &Message_Payload::ByteSizeLong,
            &Message_Payload::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_._cached_size_),
        false,
    },
    &Message_Payload::kDescriptorMethods,
    &descriptor_table_mq_5fmsg_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Message_Payload::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 39, 2> Message_Payload::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bitmq::Message_Payload>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .bitmq.BasicProperties properties = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_.properties_)}},
    // string body = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_.body_)}},
    // string valid = 3;
    {::_pbi::TcParser::FastUS1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_.valid_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .bitmq.BasicProperties properties = 1;
    {PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_.properties_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // string body = 2;
    {PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_.body_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // string valid = 3;
    {PROTOBUF_FIELD_OFFSET(Message_Payload, _impl_.valid_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
  }}, {{
    {::_pbi::TcParser::GetTable<::bitmq::BasicProperties>()},
  }}, {{
    "\25\0\4\5\0\0\0\0"
    "bitmq.Message.Payload"
    "body"
    "valid"
  }},
};

PROTOBUF_NOINLINE void Message_Payload::Clear() {
// @@protoc_insertion_point(message_clear_start:bitmq.Message.Payload)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.body_.ClearToEmpty();
  _impl_.valid_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.properties_ != nullptr);
    _impl_.properties_->Clear();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Message_Payload::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Message_Payload& this_ = static_cast<const Message_Payload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Message_Payload::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Message_Payload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:bitmq.Message.Payload)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .bitmq.BasicProperties properties = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.properties_, this_._impl_.properties_->GetCachedSize(), target,
                stream);
          }

          // string body = 2;
          if (!this_._internal_body().empty()) {
            const std::string& _s = this_._internal_body();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bitmq.Message.Payload.body");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // string valid = 3;
          if (!this_._internal_valid().empty()) {
            const std::string& _s = this_._internal_valid();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "bitmq.Message.Payload.valid");
            target = stream->WriteStringMaybeAliased(3, _s, target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:bitmq.Message.Payload)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Message_Payload::ByteSizeLong(const MessageLite& base) {
          const Message_Payload& this_ = static_cast<const Message_Payload&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Message_Payload::ByteSizeLong() const {
          const Message_Payload& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:bitmq.Message.Payload)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string body = 2;
            if (!this_._internal_body().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_body());
            }
            // string valid = 3;
            if (!this_._internal_valid().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_valid());
            }
          }
           {
            // .bitmq.BasicProperties properties = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.properties_);
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Message_Payload::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Message_Payload*>(&to_msg);
  auto& from = static_cast<const Message_Payload&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:bitmq.Message.Payload)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_body().empty()) {
    _this->_internal_set_body(from._internal_body());
  }
  if (!from._internal_valid().empty()) {
    _this->_internal_set_valid(from._internal_valid());
  }
  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.properties_ != nullptr);
    if (_this->_impl_.properties_ == nullptr) {
      _this->_impl_.properties_ =
          ::google::protobuf::Message::CopyConstruct<::bitmq::BasicProperties>(arena, *from._impl_.properties_);
    } else {
      _this->_impl_.properties_->MergeFrom(*from._impl_.properties_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Message_Payload::CopyFrom(const Message_Payload& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitmq.Message.Payload)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Message_Payload::InternalSwap(Message_Payload* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.body_, &other->_impl_.body_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.valid_, &other->_impl_.valid_, arena);
  swap(_impl_.properties_, other->_impl_.properties_);
}

::google::protobuf::Metadata Message_Payload::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class Message::_Internal {
 public:
  using HasBits =
      decltype(std::declval<Message>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Message, _impl_._has_bits_);
};

Message::Message(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:bitmq.Message)
}
inline PROTOBUF_NDEBUG_INLINE Message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::bitmq::Message& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0} {}

Message::Message(
    ::google::protobuf::Arena* arena,
    const Message& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Message* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.payload_ = (cached_has_bits & 0x00000001u) ? ::google::protobuf::Message::CopyConstruct<::bitmq::Message_Payload>(
                              arena, *from._impl_.payload_)
                        : nullptr;
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, offset_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, offset_),
           offsetof(Impl_, length_) -
               offsetof(Impl_, offset_) +
               sizeof(Impl_::length_));

  // @@protoc_insertion_point(copy_constructor:bitmq.Message)
}
inline PROTOBUF_NDEBUG_INLINE Message::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : _cached_size_{0} {}

inline void Message::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, payload_),
           0,
           offsetof(Impl_, length_) -
               offsetof(Impl_, payload_) +
               sizeof(Impl_::length_));
}
Message::~Message() {
  // @@protoc_insertion_point(destructor:bitmq.Message)
  SharedDtor(*this);
}
inline void Message::SharedDtor(MessageLite& self) {
  Message& this_ = static_cast<Message&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.payload_;
  this_._impl_.~Impl_();
}

inline void* Message::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) Message(arena);
}
constexpr auto Message::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(Message),
                                            alignof(Message));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull Message::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_Message_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &Message::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<Message>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &Message::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<Message>(), &Message::ByteSizeLong,
            &Message::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(Message, _impl_._cached_size_),
        false,
    },
    &Message::kDescriptorMethods,
    &descriptor_table_mq_5fmsg_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* Message::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 1, 0, 2> Message::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(Message, _impl_._has_bits_),
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    1,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::bitmq::Message>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // .bitmq.Message.Payload payload = 1;
    {::_pbi::TcParser::FastMtS1,
     {10, 0, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_)}},
    // uint32 offset = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Message, _impl_.offset_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.offset_)}},
    // uint32 length = 3;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Message, _impl_.length_), 63>(),
     {24, 63, 0, PROTOBUF_FIELD_OFFSET(Message, _impl_.length_)}},
  }}, {{
    65535, 65535
  }}, {{
    // .bitmq.Message.Payload payload = 1;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_), _Internal::kHasBitsOffset + 0, 0,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    // uint32 offset = 2;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.offset_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // uint32 length = 3;
    {PROTOBUF_FIELD_OFFSET(Message, _impl_.length_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
  }}, {{
    {::_pbi::TcParser::GetTable<::bitmq::Message_Payload>()},
  }}, {{
  }},
};

PROTOBUF_NOINLINE void Message::Clear() {
// @@protoc_insertion_point(message_clear_start:bitmq.Message)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.payload_ != nullptr);
    _impl_.payload_->Clear();
  }
  ::memset(&_impl_.offset_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.length_) -
      reinterpret_cast<char*>(&_impl_.offset_)) + sizeof(_impl_.length_));
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* Message::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const Message& this_ = static_cast<const Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* Message::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:bitmq.Message)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          cached_has_bits = this_._impl_._has_bits_[0];
          // .bitmq.Message.Payload payload = 1;
          if (cached_has_bits & 0x00000001u) {
            target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
                1, *this_._impl_.payload_, this_._impl_.payload_->GetCachedSize(), target,
                stream);
          }

          // uint32 offset = 2;
          if (this_._internal_offset() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                2, this_._internal_offset(), target);
          }

          // uint32 length = 3;
          if (this_._internal_length() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
                3, this_._internal_length(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:bitmq.Message)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t Message::ByteSizeLong(const MessageLite& base) {
          const Message& this_ = static_cast<const Message&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t Message::ByteSizeLong() const {
          const Message& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:bitmq.Message)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // .bitmq.Message.Payload payload = 1;
            cached_has_bits = this_._impl_._has_bits_[0];
            if (cached_has_bits & 0x00000001u) {
              total_size += 1 +
                            ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.payload_);
            }
          }
           {
            // uint32 offset = 2;
            if (this_._internal_offset() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_offset());
            }
            // uint32 length = 3;
            if (this_._internal_length() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
                  this_._internal_length());
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void Message::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Message*>(&to_msg);
  auto& from = static_cast<const Message&>(from_msg);
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:bitmq.Message)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(from._impl_.payload_ != nullptr);
    if (_this->_impl_.payload_ == nullptr) {
      _this->_impl_.payload_ =
          ::google::protobuf::Message::CopyConstruct<::bitmq::Message_Payload>(arena, *from._impl_.payload_);
    } else {
      _this->_impl_.payload_->MergeFrom(*from._impl_.payload_);
    }
  }
  if (from._internal_offset() != 0) {
    _this->_impl_.offset_ = from._impl_.offset_;
  }
  if (from._internal_length() != 0) {
    _this->_impl_.length_ = from._impl_.length_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void Message::CopyFrom(const Message& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:bitmq.Message)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Message::InternalSwap(Message* PROTOBUF_RESTRICT other) {
  using std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Message, _impl_.length_)
      + sizeof(Message::_impl_.length_)
      - PROTOBUF_FIELD_OFFSET(Message, _impl_.payload_)>(
          reinterpret_cast<char*>(&_impl_.payload_),
          reinterpret_cast<char*>(&other->_impl_.payload_));
}

::google::protobuf::Metadata Message::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace bitmq
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_mq_5fmsg_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
