// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: contacts.proto
// Protobuf C++ Version: 5.29.3

#include "contacts.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace contacts {

inline constexpr PeopleInfo::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
      : name_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        sn_{::uint64_t{0u}},
        score_{0},
        _cached_size_{0} {}

template <typename>
PROTOBUF_CONSTEXPR PeopleInfo::PeopleInfo(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct PeopleInfoDefaultTypeInternal {
  PROTOBUF_CONSTEXPR PeopleInfoDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~PeopleInfoDefaultTypeInternal() {}
  union {
    PeopleInfo _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PeopleInfoDefaultTypeInternal _PeopleInfo_default_instance_;
}  // namespace contacts
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_contacts_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_contacts_2eproto = nullptr;
const ::uint32_t
    TableStruct_contacts_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        ~0u,  // no _has_bits_
        PROTOBUF_FIELD_OFFSET(::contacts::PeopleInfo, _internal_metadata_),
        ~0u,  // no _extensions_
        ~0u,  // no _oneof_case_
        ~0u,  // no _weak_field_map_
        ~0u,  // no _inlined_string_donated_
        ~0u,  // no _split_
        ~0u,  // no sizeof(Split)
        PROTOBUF_FIELD_OFFSET(::contacts::PeopleInfo, _impl_.sn_),
        PROTOBUF_FIELD_OFFSET(::contacts::PeopleInfo, _impl_.name_),
        PROTOBUF_FIELD_OFFSET(::contacts::PeopleInfo, _impl_.score_),
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, -1, -1, sizeof(::contacts::PeopleInfo)},
};
static const ::_pb::Message* const file_default_instances[] = {
    &::contacts::_PeopleInfo_default_instance_._instance,
};
const char descriptor_table_protodef_contacts_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\016contacts.proto\022\010contacts\"5\n\nPeopleInfo"
    "\022\n\n\002sn\030\001 \001(\004\022\014\n\004name\030\002 \001(\t\022\r\n\005score\030\003 \001("
    "\002b\006proto3"
};
static ::absl::once_flag descriptor_table_contacts_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_contacts_2eproto = {
    false,
    false,
    89,
    descriptor_table_protodef_contacts_2eproto,
    "contacts.proto",
    &descriptor_table_contacts_2eproto_once,
    nullptr,
    0,
    1,
    schemas,
    file_default_instances,
    TableStruct_contacts_2eproto::offsets,
    file_level_enum_descriptors_contacts_2eproto,
    file_level_service_descriptors_contacts_2eproto,
};
namespace contacts {
// ===================================================================

class PeopleInfo::_Internal {
 public:
};

PeopleInfo::PeopleInfo(::google::protobuf::Arena* arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:contacts.PeopleInfo)
}
inline PROTOBUF_NDEBUG_INLINE PeopleInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility, ::google::protobuf::Arena* arena,
    const Impl_& from, const ::contacts::PeopleInfo& from_msg)
      : name_(arena, from.name_),
        _cached_size_{0} {}

PeopleInfo::PeopleInfo(
    ::google::protobuf::Arena* arena,
    const PeopleInfo& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, _class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  PeopleInfo* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::memcpy(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sn_),
           reinterpret_cast<const char *>(&from._impl_) +
               offsetof(Impl_, sn_),
           offsetof(Impl_, score_) -
               offsetof(Impl_, sn_) +
               sizeof(Impl_::score_));

  // @@protoc_insertion_point(copy_constructor:contacts.PeopleInfo)
}
inline PROTOBUF_NDEBUG_INLINE PeopleInfo::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* arena)
      : name_(arena),
        _cached_size_{0} {}

inline void PeopleInfo::SharedCtor(::_pb::Arena* arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char *>(&_impl_) +
               offsetof(Impl_, sn_),
           0,
           offsetof(Impl_, score_) -
               offsetof(Impl_, sn_) +
               sizeof(Impl_::score_));
}
PeopleInfo::~PeopleInfo() {
  // @@protoc_insertion_point(destructor:contacts.PeopleInfo)
  SharedDtor(*this);
}
inline void PeopleInfo::SharedDtor(MessageLite& self) {
  PeopleInfo& this_ = static_cast<PeopleInfo&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.name_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PeopleInfo::PlacementNew_(const void*, void* mem,
                                        ::google::protobuf::Arena* arena) {
  return ::new (mem) PeopleInfo(arena);
}
constexpr auto PeopleInfo::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(PeopleInfo),
                                            alignof(PeopleInfo));
}
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::google::protobuf::internal::ClassDataFull PeopleInfo::_class_data_ = {
    ::google::protobuf::internal::ClassData{
        &_PeopleInfo_default_instance_._instance,
        &_table_.header,
        nullptr,  // OnDemandRegisterArenaDtor
        nullptr,  // IsInitialized
        &PeopleInfo::MergeImpl,
        ::google::protobuf::Message::GetNewImpl<PeopleInfo>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
        &PeopleInfo::SharedDtor,
        ::google::protobuf::Message::GetClearImpl<PeopleInfo>(), &PeopleInfo::ByteSizeLong,
            &PeopleInfo::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
        PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_._cached_size_),
        false,
    },
    &PeopleInfo::kDescriptorMethods,
    &descriptor_table_contacts_2eproto,
    nullptr,  // tracker
};
const ::google::protobuf::internal::ClassData* PeopleInfo::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(_class_data_.tc_table);
  return _class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<2, 3, 0, 32, 2> PeopleInfo::_table_ = {
  {
    0,  // no _has_bits_
    0, // no _extensions_
    3, 24,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967288,  // skipmap
    offsetof(decltype(_table_), field_entries),
    3,  // num_field_entries
    0,  // num_aux_entries
    offsetof(decltype(_table_), field_names),  // no aux_entries
    _class_data_.base(),
    nullptr,  // post_loop_handler
    ::_pbi::TcParser::GenericFallback,  // fallback
    #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
    ::_pbi::TcParser::GetTable<::contacts::PeopleInfo>(),  // to_prefetch
    #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // uint64 sn = 1;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t, offsetof(PeopleInfo, _impl_.sn_), 63>(),
     {8, 63, 0, PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.sn_)}},
    // string name = 2;
    {::_pbi::TcParser::FastUS1,
     {18, 63, 0, PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.name_)}},
    // float score = 3;
    {::_pbi::TcParser::FastF32S1,
     {29, 63, 0, PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.score_)}},
  }}, {{
    65535, 65535
  }}, {{
    // uint64 sn = 1;
    {PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.sn_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt64)},
    // string name = 2;
    {PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.name_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // float score = 3;
    {PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.score_), 0, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kFloat)},
  }},
  // no aux_entries
  {{
    "\23\0\4\0\0\0\0\0"
    "contacts.PeopleInfo"
    "name"
  }},
};

PROTOBUF_NOINLINE void PeopleInfo::Clear() {
// @@protoc_insertion_point(message_clear_start:contacts.PeopleInfo)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _impl_.name_.ClearToEmpty();
  ::memset(&_impl_.sn_, 0, static_cast<::size_t>(
      reinterpret_cast<char*>(&_impl_.score_) -
      reinterpret_cast<char*>(&_impl_.sn_)) + sizeof(_impl_.score_));
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::uint8_t* PeopleInfo::_InternalSerialize(
            const MessageLite& base, ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) {
          const PeopleInfo& this_ = static_cast<const PeopleInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::uint8_t* PeopleInfo::_InternalSerialize(
            ::uint8_t* target,
            ::google::protobuf::io::EpsCopyOutputStream* stream) const {
          const PeopleInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(serialize_to_array_start:contacts.PeopleInfo)
          ::uint32_t cached_has_bits = 0;
          (void)cached_has_bits;

          // uint64 sn = 1;
          if (this_._internal_sn() != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteUInt64ToArray(
                1, this_._internal_sn(), target);
          }

          // string name = 2;
          if (!this_._internal_name().empty()) {
            const std::string& _s = this_._internal_name();
            ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
                _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "contacts.PeopleInfo.name");
            target = stream->WriteStringMaybeAliased(2, _s, target);
          }

          // float score = 3;
          if (::absl::bit_cast<::uint32_t>(this_._internal_score()) != 0) {
            target = stream->EnsureSpace(target);
            target = ::_pbi::WireFormatLite::WriteFloatToArray(
                3, this_._internal_score(), target);
          }

          if (PROTOBUF_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
            target =
                ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
                    this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
          }
          // @@protoc_insertion_point(serialize_to_array_end:contacts.PeopleInfo)
          return target;
        }

#if defined(PROTOBUF_CUSTOM_VTABLE)
        ::size_t PeopleInfo::ByteSizeLong(const MessageLite& base) {
          const PeopleInfo& this_ = static_cast<const PeopleInfo&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
        ::size_t PeopleInfo::ByteSizeLong() const {
          const PeopleInfo& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
          // @@protoc_insertion_point(message_byte_size_start:contacts.PeopleInfo)
          ::size_t total_size = 0;

          ::uint32_t cached_has_bits = 0;
          // Prevent compiler warnings about cached_has_bits being unused
          (void)cached_has_bits;

          ::_pbi::Prefetch5LinesFrom7Lines(&this_);
           {
            // string name = 2;
            if (!this_._internal_name().empty()) {
              total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                              this_._internal_name());
            }
            // uint64 sn = 1;
            if (this_._internal_sn() != 0) {
              total_size += ::_pbi::WireFormatLite::UInt64SizePlusOne(
                  this_._internal_sn());
            }
            // float score = 3;
            if (::absl::bit_cast<::uint32_t>(this_._internal_score()) != 0) {
              total_size += 5;
            }
          }
          return this_.MaybeComputeUnknownFieldsSize(total_size,
                                                     &this_._impl_._cached_size_);
        }

void PeopleInfo::MergeImpl(::google::protobuf::MessageLite& to_msg, const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<PeopleInfo*>(&to_msg);
  auto& from = static_cast<const PeopleInfo&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:contacts.PeopleInfo)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if (from._internal_sn() != 0) {
    _this->_impl_.sn_ = from._impl_.sn_;
  }
  if (::absl::bit_cast<::uint32_t>(from._internal_score()) != 0) {
    _this->_impl_.score_ = from._impl_.score_;
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void PeopleInfo::CopyFrom(const PeopleInfo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:contacts.PeopleInfo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void PeopleInfo::InternalSwap(PeopleInfo* PROTOBUF_RESTRICT other) {
  using std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, &other->_impl_.name_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.score_)
      + sizeof(PeopleInfo::_impl_.score_)
      - PROTOBUF_FIELD_OFFSET(PeopleInfo, _impl_.sn_)>(
          reinterpret_cast<char*>(&_impl_.sn_),
          reinterpret_cast<char*>(&other->_impl_.sn_));
}

::google::protobuf::Metadata PeopleInfo::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace contacts
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ PROTOBUF_UNUSED =
        (::_pbi::AddDescriptors(&descriptor_table_contacts_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
